### ISSUE TITLE
Test results show same size for all stack frames

### ISSUE THREAD

**Issue by jasonwilliams** [jonhoo/inferno#162]
Taken from https://github.com/flamegraph-rs/flamegraph/issues/76

![image](https://user-images.githubusercontent.com/936006/75398394-74e8d500-58f1-11ea-920f-6ad90e6a00c4.png)

**Steps to reproduce**
* Clone https://github.com/jasonwilliams/boa
* Start the docker container with the image provided (i do this via vscode)
* Install `perf`  - ` sudo apt-get install linux-perf`
* Run `cargo flamegraph --dev --bin boa_cli`
* Open up the flamegraph.svg

I also get an error when I try other options.
removing --dev or adding —freq i did get 
```
undefined[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.006 MB perf.data ]
thread 'main' panicked at 'assertion failed: self.event_filter.is_some()', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/inferno-0.9.4/src/collapse/perf.rs:165:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: std::panicking::begin_panic
  12: <T as inferno::collapse::Collapse>::collapse
  13: flamegraph::generate_flamegraph_for_workload
  14: cargo_flamegraph::main
  15: std::rt::lang_start::{{closure}}
  16: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  17: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  18: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  19: std::panicking::try
             at src/libstd/panicking.rs:270
  20: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  21: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  22: main
  23: __libc_start_main
  24: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jonhoo** [comment]
Hmm, interesting. Could you post the output of `perf script` somewhere if it's not too large?

**Comment by jasonwilliams** [comment]
```
boa_cli 12937 10360.271071:   10101010 cpu-clock:uhH: 
            562039122f0f <std::collections::hash::map::HashMap<K,V> as gc::trace::Trace>::trace+0xbf (/workspaces/boa/target/debug/boa_c
li)
            56203912789e <alloc::boxed::Box<T> as gc::trace::Trace>::trace::mark+0xe (/workspaces/boa/target/debug/boa_cli)
            562039148b50 <alloc::boxed::Box<T> as gc::trace::Trace>::trace+0x20 (/workspaces/boa/target/debug/boa_cli)
            5620391b9e5e <boa::builtins::object::Object as gc::trace::Trace>::trace::mark+0xe (/workspaces/boa/target/debug/boa_cli)
            56203917a598 <boa::builtins::object::Object as gc::trace::Trace>::trace+0x68 (/workspaces/boa/target/debug/boa_cli)
            5620391ca6bd <boa::builtins::function::NativeFunction as gc::trace::Trace>::trace::mark+0xd (/workspaces/boa/target/debug/bo
a_cli)
            5620391b9470 <boa::builtins::function::NativeFunction as gc::trace::Trace>::trace+0x20 (/workspaces/boa/target/debug/boa_cli
)
            5620391ca53d <boa::builtins::function::Function as gc::trace::Trace>::trace::mark+0xd (/workspaces/boa/target/debug/boa_cli)
            5620391b8da6 <boa::builtins::function::Function as gc::trace::Trace>::trace+0x36 (/workspaces/boa/target/debug/boa_cli)
            56203915fcfa <gc::GcCell<T> as gc::trace::Trace>::trace+0x5a (/workspaces/boa/target/debug/boa_cli)
            56203912787e <alloc::boxed::Box<T> as gc::trace::Trace>::trace::mark+0xe (/workspaces/boa/target/debug/boa_cli)
            562039148a90 <alloc::boxed::Box<T> as gc::trace::Trace>::trace+0x20 (/workspaces/boa/target/debug/boa_cli)
            562039126b6e <boa::builtins::value::ValueData as gc::trace::Trace>::trace::mark+0xe (/workspaces/boa/target/debug/boa_cli)
            56203915ace0 <boa::builtins::value::ValueData as gc::trace::Trace>::trace+0xe0 (/workspaces/boa/target/debug/boa_cli)
            5620391bc62a gc::gc::GcBox<T>::trace_inner+0x5a (/workspaces/boa/target/debug/boa_cli)
            56203915ef63 <gc::Gc<T> as gc::trace::Trace>::trace+0x23 (/workspaces/boa/target/debug/boa_cli)
            562039127b8e <core::option::Option<T> as gc::trace::Trace>::trace::mark+0xe (/workspaces/boa/target/debug/boa_cli)
            5620391c9761 <core::option::Option<T> as gc::trace::Trace>::trace+0x41 (/workspaces/boa/target/debug/boa_cli)
            56203917b5fe <boa::builtins::property::Property as gc::trace::Trace>::trace::mark+0xe (/workspaces/boa/target/debug/boa_cli)
            562039166a37 <boa::builtins::property::Property as gc::trace::Trace>::trace+0x87 (/workspaces/boa/target/debug/boa_cli)
            562039127e2d <std::collections::hash::map::HashMap<K,V> as gc::trace::Trace>::trace::mark+0xd (/workspaces/boa/target/debug/
boa_cli)
            56203912306a <std::collections::hash::map::HashMap<K,V> as gc::trace::Trace>::trace+0x10a (/workspaces/boa/target/debug/boa_
cli)
            56203912785e <alloc::boxed::Box<T> as gc::trace::Trace>::trace::mark+0xe (/workspaces/boa/target/debug/boa_cli)
            562039148ac0 <alloc::boxed::Box<T> as gc::trace::Trace>::trace+0x20 (/workspaces/boa/target/debug/boa_cli)
            5620391b9dfe <boa::builtins::object::Object as gc::trace::Trace>::trace::mark+0xe (/workspaces/boa/target/debug/boa_cli)
            56203917a5a3 <boa::builtins::object::Object as gc::trace::Trace>::trace+0x73 (/workspaces/boa/target/debug/boa_cli)
            56203915fc8a <gc::GcCell<T> as gc::trace::Trace>::trace+0x5a (/workspaces/boa/target/debug/boa_cli)
            562039126b8e <boa::builtins::value::ValueData as gc::trace::Trace>::trace::mark+0xe (/workspaces/boa/target/debug/boa_cli)
            56203915acc3 <boa::builtins::value::ValueData as gc::trace::Trace>::trace+0xc3 (/workspaces/boa/target/debug/boa_cli)
            5620391bc62a gc::gc::GcBox<T>::trace_inner+0x5a (/workspaces/boa/target/debug/boa_cli)
            56203915ef63 <gc::Gc<T> as gc::trace::Trace>::trace+0x23 (/workspaces/boa/target/debug/boa_cli)
            562039127b8e <core::option::Option<T> as gc::trace::Trace>::trace::mark+0xe (/workspaces/boa/target/debug/boa_cli)
            5620391c9761 <core::option::Option<T> as gc::trace::Trace>::trace+0x41 (/workspaces/boa/target/debug/boa_cli)
            56203917b5fe <boa::builtins::property::Property as gc::trace::Trace>::trace::mark+0xe (/workspaces/boa/target/debug/boa_cli)
            562039166a37 <boa::builtins::property::Property as gc::trace::Trace>::trace+0x87 (/workspaces/boa/target/debug/boa_cli)
            562039127e2d <std::collections::hash::map::HashMap<K,V> as gc::trace::Trace>::trace::mark+0xd (/workspaces/boa/target/debug/
boa_cli)
            56203912306a <std::collections::hash::map::HashMap<K,V> as gc::trace::Trace>::trace+0x10a (/workspaces/boa/target/debug/boa_
cli)
            56203912785e <alloc::boxed::Box<T> as gc::trace::Trace>::trace::mark+0xe (/workspaces/boa/target/debug/boa_cli)
            562039148ac0 <alloc::boxed::Box<T> as gc::trace::Trace>::trace+0x20 (/workspaces/boa/target/debug/boa_cli)
            5620391b9dfe <boa::builtins::object::Object as gc::trace::Trace>::trace::mark+0xe (/workspaces/boa/target/debug/boa_cli)
            56203917a5a3 <boa::builtins::object::Object as gc::trace::Trace>::trace+0x73 (/workspaces/boa/target/debug/boa_cli)
            56203915fc8a <gc::GcCell<T> as gc::trace::Trace>::trace+0x5a (/workspaces/boa/target/debug/boa_cli)
            562039126b8e <boa::builtins::value::ValueData as gc::trace::Trace>::trace::mark+0xe (/workspaces/boa/target/debug/boa_cli)
            56203915acc3 <boa::builtins::value::ValueData as gc::trace::Trace>::trace+0xc3 (/workspaces/boa/target/debug/boa_cli)
            5620391bc62a gc::gc::GcBox<T>::trace_inner+0x5a (/workspaces/boa/target/debug/boa_cli)
            56203915ef63 <gc::Gc<T> as gc::trace::Trace>::trace+0x23 (/workspaces/boa/target/debug/boa_cli)
            562039127b8e <core::option::Option<T> as gc::trace::Trace>::trace::mark+0xe (/workspaces/boa/target/debug/boa_cli)
            5620391c9761 <core::option::Option<T> as gc::trace::Trace>::trace+0x41 (/workspaces/boa/target/debug/boa_cli)
            56203917b5fe <boa::builtins::property::Property as gc::trace::Trace>::trace::mark+0xe (/workspaces/boa/target/debug/boa_cli)
            562039166a37 <boa::builtins::property::Property as gc::trace::Trace>::trace+0x87 (/workspaces/boa/target/debug/boa_cli)
            562039127e2d <std::collections::hash::map::HashMap<K,V> as gc::trace::Trace>::trace::mark+0xd (/workspaces/boa/target/debug/
boa_cli)
            56203912306a <std::collections::hash::map::HashMap<K,V> as gc::trace::Trace>::trace+0x10a (/workspaces/boa/target/debug/boa_
cli)
            56203912785e <alloc::boxed::Box<T> as gc::trace::Trace>::trace::mark+0xe (/workspaces/boa/target/debug/boa_cli)
            562039148ac0 <alloc::boxed::Box<T> as gc::trace::Trace>::trace+0x20 (/workspaces/boa/target/debug/boa_cli)
            5620391b9dfe <boa::builtins::object::Object as gc::trace::Trace>::trace::mark+0xe (/workspaces/boa/target/debug/boa_cli)
            56203917a5a3 <boa::builtins::object::Object as gc::trace::Trace>::trace+0x73 (/workspaces/boa/target/debug/boa_cli)
            56203915fc8a <gc::GcCell<T> as gc::trace::Trace>::trace+0x5a (/workspaces/boa/target/debug/boa_cli)
            562039126b8e <boa::builtins::value::ValueData as gc::trace::Trace>::trace::mark+0xe (/workspaces/boa/target/debug/boa_cli)
            56203915acc3 <boa::builtins::value::ValueData as gc::trace::Trace>::trace+0xc3 (/workspaces/boa/target/debug/boa_cli)
            5620391bc62a gc::gc::GcBox<T>::trace_inner+0x5a (/workspaces/boa/target/debug/boa_cli)
            56203915ef63 <gc::Gc<T> as gc::trace::Trace>::trace+0x23 (/workspaces/boa/target/debug/boa_cli)
            5620391b95fe <boa::environment::object_environment_record::ObjectEnvironmentRecord as gc::trace::Trace>::trace::mark+0xe (/w
orkspaces/boa/target/debug/boa_cli)
            5620391b4bbd <boa::environment::object_environment_record::ObjectEnvironmentRecord as gc::trace::Trace>::trace+0x3d (/worksp
aces/boa/target/debug/boa_cli)
            5620391277ed <alloc::boxed::Box<T> as gc::trace::Trace>::trace::mark+0xd (/workspaces/boa/target/debug/boa_cli)
            562039148be0 <alloc::boxed::Box<T> as gc::trace::Trace>::trace+0x20 (/workspaces/boa/target/debug/boa_cli)
            5620391cb52e <boa::environment::global_environment_record::GlobalEnvironmentRecord as gc::trace::Trace>::trace::mark+0xe (/w
orkspaces/boa/target/debug/boa_cli)
            5620391336e8 <boa::environment::global_environment_record::GlobalEnvironmentRecord as gc::trace::Trace>::trace+0x48 (/worksp
aces/boa/target/debug/boa_cli)
            5620391278ed <alloc::boxed::Box<T> as gc::trace::Trace>::trace::mark+0x1d (/workspaces/boa/target/debug/boa_cli)
            562039148af4 <alloc::boxed::Box<T> as gc::trace::Trace>::trace+0x24 (/workspaces/boa/target/debug/boa_cli)
            56203915fddb <gc::GcCell<T> as gc::trace::Trace>::trace+0x5b (/workspaces/boa/target/debug/boa_cli)
            5620394a6c7a gc::gc::GcBox<T>::trace_inner+0x7a (/workspaces/boa/target/debug/boa_cli)
            5620394a6f7c gc::gc::collect_garbage::mark+0xdc (/workspaces/boa/target/debug/boa_cli)
            5620394a6d95 gc::gc::collect_garbage+0x105 (/workspaces/boa/target/debug/boa_cli)
            5620391bcf1e gc::gc::GcBox$LT$T$GT$::new::_$u7b$$u7b$closure$u7d$$u7d$::ha2ed0674a1c3dc9f+0x10e (/workspaces/boa/target/debu
g/boa_cli)
            5620391e3b80 std::thread::local::LocalKey<T>::try_with+0x140 (/workspaces/boa/target/debug/boa_cli)
            5620391e385c std::thread::local::LocalKey<T>::with+0x3c (/workspaces/boa/target/debug/boa_cli)
            5620391bc889 gc::gc::GcBox<T>::new+0x39 (/workspaces/boa/target/debug/boa_cli)
            56203915d08a gc::Gc<T>::new+0x9a (/workspaces/boa/target/debug/boa_cli)
            5620390d2626 <alloc::string::String as boa::builtins::value::ToValue>::to_value+0x46 (/workspaces/boa/target/debug/boa_cli)
            562039126731 boa::builtins::value::to_value+0x11 (/workspaces/boa/target/debug/boa_cli)
            5620391774a5 <boa::builtins::object::Object as boa::builtins::object::internal_methods_trait::ObjectInternalMethods>::define
_own_property+0x85 (/workspaces/boa/target/debug/boa_cli)
            5620391b9b8e boa::builtins::object::internal_methods_trait::ObjectInternalMethods::set+0x31e (/workspaces/boa/target/debug/b
oa_cli)
            5620391538f4 boa::builtins::value::ValueData::set_field+0x5f4 (/workspaces/boa/target/debug/boa_cli)
            562039153eda boa::builtins::value::ValueData::set_field_slice+0xaa (/workspaces/boa/target/debug/boa_cli)
            562039140793 boa::builtins::console::create_constructor+0x163 (/workspaces/boa/target/debug/boa_cli)
            5620390e95fe boa::realm::Realm::create_instrinsics+0x39e (/workspaces/boa/target/debug/boa_cli)
            5620390e9127 boa::realm::Realm::create+0x167 (/workspaces/boa/target/debug/boa_cli)
            562038f4dd49 boa_cli::main+0x59 (/workspaces/boa/target/debug/boa_cli)
        ffffffffffffffff [unknown] ([unknown])
```

**Comment by jonhoo** [comment]
Hmm, this _looks_ like you just have a single sample, in which case all the stack frames should be the same size?

**Comment by jasonwilliams** [comment]
Do you know why there’s just a single sample though? When I the same command on my Mac I have multiple samples.

**Comment by jonhoo** [comment]
That I don't know -- seems like it is probably an issue with how `cargo flamegraph` collects samples.

**Comment by jasonwilliams** [comment]
Still not able to get past:
```
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.006 MB perf.data ]
thread 'main' panicked at 'assertion failed: self.event_filter.is_some()', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/inferno-0.
9.5/src/collapse/perf.rs:165:9
```

**Comment by jonhoo** [comment]
So, the crash there in inferno is unfortunate, but the underlying cause is still the same — the `perf record` is not producing any samples, so inferno has nothing to operate on. We can fix the assertion failure (we should probably just return `Ok()` instead), but that won't actually solve your problem :)

**Comment by jasonwilliams** [comment]
That’s fine, I think fixing the error may help anyone in future who comes across this too, maybe with a helpful message?

As for perf record not producing any samples I’ll take a look. I opened a new issue for this error, I’m guessing the answer to that is the same

**Comment by jonhoo** [comment]
It actually looks like there was a deeper issue going on. Take a look at #168 if you're curious! Thanks for reporting it.

As for why you are only getting a single sample (which is lost due to one of the bugs fixed by #168), it's probably because the program doesn't run for long enough. `perf` is a sampling profiler, so it needs the program to run for a while for it to collect enough samples to produce a meaningful profile.

**Comment by jasonwilliams** [comment]
thank you for investigating!

I’ll follow https://gendignoux.com/blog/2019/11/09/profiling-rust-docker-perf.html as running the same command directly on my Mac it works much better, so I thinks there’s some docker limitation at play also.
